config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :leads
  resources :blog_posts

  get 'pages/home', to: 'pages#home', as: :home
  get 'pages/terms', to: 'pages#terms', as: :terms
  get 'pages/privacy', to: 'pages#privacy', as: :privacy

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Non resource routes:
  get 'my_posts', to: 'blog_posts#my_posts', as: :my_posts
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/blog_post.rb
# frozen_string_literal: true

class BlogPost < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_rich_text :content
  has_one_attached :image

  validates :title, presence: true
  validates :content, presence: true

  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where('published_at <= ?', Time.current).order(published_at: :desc) }
  scope :scheduled, -> { where('published_at > ?', Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def schedule?
    published_at? && published_at > Time.current
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_blog_post, only: %i[show edit update destroy]

  # GET /blog_posts or /blog_posts.json
  def index
    @blog_posts = BlogPost.published
    redirect_to root_path, notice: 'No blog posts found' if @blog_posts.empty?
  end

  def my_posts
    @blog_posts = current_user.blog_posts
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
    @blog_posts = BlogPost.published
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit; end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)
    @blog_post.author = current_user

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to blog_post_url(@blog_post), notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to blog_post_url(@blog_post), notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy!

    respond_to do |format|
      format.html { redirect_to my_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog_post
    @blog_post = BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, notice: 'Blog post not found'
  end

  # Only allow a list of trusted parameters through.
  def blog_post_params
    params.require(:blog_post).permit(:title, :published_at, :content, :image)
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  def read_time(blog_post)
    word_count = blog_post.content.body.to_plain_text.split.size
    (word_count / 200.0).ceil
  end

  def formatted_publication_date(blog_post)
    return blog_post.published_at.strftime('%b %e') if blog_post.published_at.year == Date.current.year

    blog_post.published_at.strftime('%b %e, %Y')
  end
end

app/views/blog_posts/_blog_post.html.erb
<%= turbo_frame_tag @blog_post do%>
  <!-- Blog Article -->
  <div class="max-w-3xl px-4 pt-6 lg:pt-10 pb-12 sm:px-6 lg:px-8 mx-auto" id="<%= dom_id blog_post %>">
    <div class="max-w-2xl">
      <!-- Avatar Media -->
      <div class="flex justify-between items-center mb-6">
        <div class="flex w-full sm:items-center gap-x-5 sm:gap-x-3">
          <div class="flex-shrink-0">
            <%= show_avatar %>
          </div>
          <div class="grow">
            <div class="flex justify-between items-center gap-x-2">
              <div>
                <!-- Tooltip -->
                <div class="hs-tooltip inline-block [--trigger:hover] [--placement:bottom]">
                  <div class="hs-tooltip-toggle sm:mb-1 block text-start cursor-pointer">
                    <span class="font-semibold text-gray-800 dark:text-gray-200">
                      <%= blog_post.author.name %> <%# <span class="text-gray-500 text-xs"> - Full Stack Developer</span> %>
                    </span>
                  </div>
                </div>
                <!-- End Tooltip -->
                <ul class="text-xs text-gray-500">
                  <li class="inline-block relative pe-6 last:pe-0 last-of-type:before:hidden before:absolute before:top-1/2 before:end-2 before:-translate-y-1/2 before:w-1 before:h-1 before:bg-gray-300 before:rounded-full dark:text-gray-400 dark:before:bg-gray-600">
                    <%= formatted_publication_date(blog_post) %>
                  </li>
                  <li class="inline-block relative pe-6 last:pe-0 last-of-type:before:hidden before:absolute before:top-1/2 before:end-2 before:-translate-y-1/2 before:w-1 before:h-1 before:bg-gray-300 before:rounded-full dark:text-gray-400 dark:before:bg-gray-600">
                    <%= read_time(blog_post) %> min read 
                  </li>
                </ul>
              </div>
              <!-- Button Group -->
              <div>
                <button type="button" class="py-1.5 px-2.5 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-white dark:hover:bg-gray-800 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
                  <svg class="w-3.5 h-3.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                  </svg>
                  Tweet
                </button>
              </div>
              <!-- End Button Group -->
            </div>
          </div>
        </div>
      </div>
      <!-- End Avatar Media -->
      <!-- Content -->
      <div class="space-y-5 md:space-y-8">
        <div class=" prose lg:prose-xl space-y-3">
          <h2 class="text-2xl font-bold md:text-3xl dark:text-white"><%= @blog_post.title %></h2>
          <%= @blog_post.content %>
          <%#--
          </div>
          <!-- Tags -->
          <div>
            <a class="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:text-gray-200 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" href="#">
              Plan
            </a>
            <a class="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:text-gray-200 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" href="#">
              Web development
            </a>
            <a class="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:text-gray-200 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" href="#">
              Free
            </a>
            <a class="m-1 inline-flex items-center gap-1.5 py-2 px-3 rounded-full text-sm bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:text-gray-200 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" href="#">
              Team
            </a>
          </div>
          %>
          <!-- End Tags -->
        </div>
        <!-- End Content -->
      </div>
    </div>
    <div class="p-8"></div>
    <hr>
    <!-- End Blog Article -->
    <!-- Sticky Share Group -->
    <%# <div class="sticky bottom-6 inset-x-0 text-center">
      <div class="inline-block bg-white shadow-md rounded-full py-3 px-4 dark:bg-gray-800">
        <div class="flex items-center gap-x-1.5">
          <!-- Button -->
          <div class="hs-tooltip inline-block">
            <button type="button" class="hs-tooltip-toggle flex items-center gap-x-2 text-sm text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
              <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>
              875
              <span class="hs-tooltip-content hs-tooltip-shown:opacity-100 hs-tooltip-shown:visible opacity-0 transition-opacity inline-block absolute invisible z-10 py-1 px-2 bg-gray-900 text-xs font-medium text-white rounded shadow-sm dark:bg-black" role="tooltip">
                Like
              </span>
            </button>
          </div>
          <!-- Button -->
          <div class="block h-3 border-e border-gray-300 mx-3 dark:border-gray-600"></div>
          <!-- Button -->
          <div class="hs-tooltip inline-block">
            <button type="button" class="hs-tooltip-toggle flex items-center gap-x-2 text-sm text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
              <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 21 1.9-5.7a8.5 8.5 0 1 1 3.8 3.8z"/></svg>
              16
              <span class="hs-tooltip-content hs-tooltip-shown:opacity-100 hs-tooltip-shown:visible opacity-0 transition-opacity inline-block absolute invisible z-10 py-1 px-2 bg-gray-900 text-xs font-medium text-white rounded shadow-sm dark:bg-black" role="tooltip">
                Comment
              </span>
            </button>
          </div>
          <!-- Button -->
          <div class="block h-3 border-e border-gray-300 mx-3 dark:border-gray-600"></div>
          <!-- Button -->
          <div class="hs-dropdown relative inline-flex">
            <button type="button" id="blog-article-share-dropdown" class="hs-dropdown-toggle flex items-center gap-x-2 text-sm text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600">
              <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" x2="12" y1="2" y2="15"/></svg>
              Share
            </button>
            <div class="hs-dropdown-menu w-56 transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden mb-1 z-10 bg-gray-900 shadow-md rounded-xl p-2 dark:bg-black" aria-labelledby="blog-article-share-dropdown">
              <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-400 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-gray-400" href="#">
                <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>
                Copy link
              </a>
              <div class="border-t border-gray-600 my-2"></div>
              <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-400 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-gray-400" href="#">
                <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                </svg>
                Share on Twitter
              </a>
              <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-400 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-gray-400" href="#">
                <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg>
                Share on Facebook
              </a>
              <a class="flex items-center gap-x-3.5 py-2 px-3 rounded-lg text-sm text-gray-400 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-gray-400" href="#">
                <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                </svg>
                Share on LinkedIn
              </a>
            </div>
          </div>
          <!-- Button -->
        </div>
      </div>
    </div> %>
    <!-- End Sticky Share Group -->
  <% end %>

app/views/blog_posts/_card.html.erb
<!-- Card -->
<%= link_to blog_post, class: "group hover:bg-gray-100 rounded-xl p-5 transition-all dark:hover:bg-white/[.05]"  do %>
  <div class="aspect-w-16 aspect-h-10">
    <%# <img class="w-full object-cover rounded-xl" src="https://images.unsplash.com/photo-1661956602116-aa6865609028?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1064&q=80" alt="Image Description"> %>
    <% if blog_post.image.present? %>
      <%= image_tag blog_post.image, class: "w-full object-cover rounded-xl"%>
    <% end %>
  </div>
  <h3 class="mt-5 text-xl text-gray-800 dark:text-gray-300 dark:hover:text-white">
    <%= blog_post.title%>
  </h3>
  <p class="mt-3 inline-flex items-center gap-x-1 text-sm font-semibold text-gray-800 dark:text-gray-200">
    Learn more
    <svg class="flex-shrink-0 w-4 h-4 transition ease-in-out group-hover:translate-x-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>
  </p>
<% end %>
<!-- End Card -->

app/views/blog_posts/_card_group.html.erb
<div class="grid lg:grid-cols-2 gap-6">
</div>
<!-- Card Blog -->
<div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
  <!-- Title -->
  <div class="max-w-2xl mx-auto text-center mb-10 lg:mb-14">
    <h2 class="text-2xl font-bold md:text-4xl md:leading-tight dark:text-white">Recent articles</h2>
    <p class="mt-1 text-gray-600 dark:text-gray-400">Explore my latest articles, where I share insights and experiences from my full-stack development journey.</p>
  </div>
  <!-- End Title -->
  <!-- Grid -->
  <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @blog_posts.offset(1).each do |blog_post| %>
      <%= render "card", blog_post: blog_post %>
    <% end %>
  </div>
  <!-- End Grid -->
</div>
<!-- End Card Blog -->

app/views/blog_posts/_dashboard_item.html.erb
<tr class="border-b dark:border-gray-700">
  <th scope="row" class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= blog_post.title %></th>
  <td class="px-4 py-3 max-w-[12rem] truncate"><%= blog_post.title %></td>
  <td class="px-4 py-3">TODO</td>
  <td class="px-4 py-3">STATUS</td>
  <td class="px-4 py-3"><%= blog_post.published_at %></td>
  <td class="px-4 py-3 flex items-center justify-evenly gap-2  ">
    <%# view %>
    <%= link_to blog_post do %>
      <svg class="flex-shrink-0 w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 14">
        <g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
          <path d="M10 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
          <path d="M10 13c4.97 0 9-2.686 9-6s-4.03-6-9-6-9 2.686-9 6 4.03 6 9 6Z"/>
        </g>
      </svg>
    <% end %>
    <%# edit %>
    <%= link_to edit_blog_post_path(blog_post) do%>
      <svg class="flex-shrink-0 w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
        <path d="M12.687 14.408a3.01 3.01 0 0 1-1.533.821l-3.566.713a3 3 0 0 1-3.53-3.53l.713-3.566a3.01 3.01 0 0 1 .821-1.533L10.905 2H2.167A2.169 2.169 0 0 0 0 4.167v11.666A2.169 2.169 0 0 0 2.167 18h11.666A2.169 2.169 0 0 0 16 15.833V11.1l-3.313 3.308Zm5.53-9.065.546-.546a2.518 2.518 0 0 0 0-3.56 2.576 2.576 0 0 0-3.559 0l-.547.547 3.56 3.56Z"/>
        <path d="M13.243 3.2 7.359 9.081a.5.5 0 0 0-.136.256L6.51 12.9a.5.5 0 0 0 .59.59l3.566-.713a.5.5 0 0 0 .255-.136L16.8 6.757 13.243 3.2Z"/>
      </svg>
    <% end %>
    <%# destroy %>
    <%= link_to blog_post, data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' } do %>
      <svg class="flex-shrink-0 w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h16M7 8v8m4-8v8M7 1h4a1 1 0 0 1 1 1v3H6V2a1 1 0 0 1 1-1ZM3 5h12v13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V5Z"/>
      </svg>
    <% end %>
  </td>
</tr>

app/views/blog_posts/_form.html.erb
<div class="border border-gray-200 rounded-lg overflow-hidden dark:border-gray-700 mx-7">
  <%= form_with(model: blog_post) do |form| %>
    <% if blog_post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>
        <ul>
          <% blog_post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :image, style:"display: block" %>
      <%= form.file_field(:image, accept: 'image/png,image/gif,image/jpeg') %>
    </div>
    <div>
      <%= form.label :content, style: "display: block" %>
      <%= form.rich_text_area :content %>
    </div>
    <div>
      <%= form.label :published_at, style: "display: block" %>
      <%= form.datetime_select :published_at, include_blank: true, selected: Time.now + (5 * 60)%>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/blog_posts/_section_card.html.erb
<% comment do %>
  <!-- Card -->
  <%= link_to blog_post, class:"group block rounded-xl dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" do%>
    <div class="aspect-w-16 aspect-h-9">
      <%= image_tag blog_post.image, class:"w-full object-cover rounded-xl" %>
    </div>
    <h3 class="mt-2 text-lg font-medium text-gray-800 group-hover:text-blue-600 dark:text-gray-300 dark:group-hover:text-white">
      <%= blog_post.title %>
    </h3>
    <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
      <%= blog_post.published_at.strftime('%b %e') %>
    </p>
  <% end %>
  <!-- End Card -->
<% end %>
<!-- Card -->
<%= link_to blog_post, className:"group flex flex-col h-full border border-gray-200 hover:border-transparent hover:shadow-lg transition-all duration-300 rounded-xl p-5 dark:border-gray-700 dark:hover:border-transparent dark:hover:shadow-black/[.4] dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600" do %>
  <div class="aspect-w-16 aspect-h-11">
    <%= image_tag blog_post.image, class:"w-full object-cover rounded-xl" %>
  </div>
  <div class="my-6">
    <h3 class="text-xl font-semibold text-gray-800 dark:text-gray-300 dark:group-hover:text-white">
      <%= blog_post.title %>
    </h3>
    <p class="mt-5 text-gray-600 dark:text-gray-400 line-clamp-2">
      <%= truncate(blog_post.content.body.to_plain_text, length: 100, separator: ' ') %>
    </p>
  </div>
  <div class="mt-auto flex items-center gap-x-3">
    <%= image_tag @owner.avatar.variant(resize_to_limit: [100,100]), class:"w-8 h-8 rounded-full" %>
    <div>
      <h5 class="text-sm text-gray-800 dark:text-gray-200">By <%= blog_post.author.name %></h5>
    </div>
  </div>
<% end %>
<!-- End Card -->

app/views/blog_posts/edit.html.erb
<h1>Editing blog post</h1>
<%= render "form", blog_post: @blog_post %>
<br>
<div>
  <%= link_to "View as guest", @blog_post %> |
  <%= link_to " <- Back to posts dashboard", my_posts_path %>
</div>

app/views/blog_posts/new.html.erb
<h1>New blog post</h1>
<%= render "form", blog_post: @blog_post %>
<br>
<div>
  <%= link_to "Back to posts dashboard", my_posts_path %>
</div>
d

app/views/blog_posts/show.html.erb
<%= render @blog_post%>
<% posts = @blog_posts.where.not(id: @blog_post.id) %>
<!-- Section Index -->
<% if posts.count > 0 %>
  <%= render "section_index", blog_posts: posts %>
<% end %>
<!-- End Section Index -->