config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :leads
  resources :blog_posts

  get 'pages/home', to: 'pages#home', as: :home
  get 'pages/terms', to: 'pages#terms', as: :terms
  get 'pages/privacy', to: 'pages#privacy', as: :privacy

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Non resource routes:
  get 'my_posts', to: 'blog_posts#my_posts', as: :my_posts
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/lead.rb
class Lead < ApplicationRecord
  # Ensure that name, email, and phone_number are present
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone_number, presence: true, numericality: true, length: { minimum: 10, maximum: 15 }

  # You can add more details about the format you expect for the phone_number
  # For example, if you expect the phone_number to only contain digits,
  # you can use a regular expression to validate the format:
  validates :phone_number, format: { with: /\A\d+\z/, message: 'only allows numbers' }

  # You can also validate the uniqueness of email if you want each lead to have a unique email address
  validates :email, uniqueness: true
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[show edit update destroy]

  # GET /leads or /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1 or /leads/1.json
  def show; end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit; end

  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to lead_url(@lead), notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to lead_url(@lead), notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy!

    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lead
    @lead = Lead.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lead_params
    params.require(:lead).permit(:name, :email, :phone_number, :details)
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_with(model: lead, class: "contents") do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :details %>
    <%= form.text_area :details, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/leads/_lead.html.erb
<div id="<%= dom_id lead %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= lead.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= lead.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone number:</strong>
    <%= lead.phone_number %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Details:</strong>
    <%= lead.details %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this lead", lead, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this lead", edit_lead_path(lead), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/leads/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lead</h1>

  <%= render "form", lead: @lead %>

  <%= link_to "Show this lead", @lead, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to leads", leads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/leads/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Leads</h1>
    <%= link_to "New lead", new_lead_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="leads" class="min-w-full">
    <%= render @leads %>
  </div>
</div>

app/views/leads/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lead</h1>

  <%= render "form", lead: @lead %>

  <%= link_to "Back to leads", leads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/leads/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @lead %>

    <%= link_to "Edit this lead", edit_lead_path(@lead), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this lead", lead_path(@lead), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to leads", leads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>